# Generated by Django 4.2.7 on 2025-08-23 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the migration job', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the migration job', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the migration job')),
                ('sei_contract_addresses', models.JSONField(default=list, help_text='List of Sei contract addresses to migrate')),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='Number of NFTs to process in each batch')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', help_text='Current job status', max_length=20)),
                ('total_nfts', models.PositiveIntegerField(default=0, help_text='Total number of NFTs to migrate')),
                ('processed_nfts', models.PositiveIntegerField(default=0, help_text='Number of NFTs processed')),
                ('successful_migrations', models.PositiveIntegerField(default=0, help_text='Number of successful migrations')),
                ('failed_migrations', models.PositiveIntegerField(default=0, help_text='Number of failed migrations')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the job started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job completed', null=True)),
                ('configuration', models.JSONField(default=dict, help_text='Job configuration parameters')),
                ('results', models.JSONField(default=dict, help_text='Job execution results and statistics')),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed')),
                ('created_by', models.ForeignKey(help_text='User who created the migration job', on_delete=django.db.models.deletion.PROTECT, related_name='created_migration_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migration Job',
                'verbose_name_plural': 'Migration Jobs',
                'db_table': 'blockchain_migration_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeiNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('sei_contract_address', models.CharField(db_index=True, help_text='Sei contract address for the NFT collection', max_length=64)),
                ('sei_token_id', models.CharField(db_index=True, help_text='Token ID on Sei blockchain', max_length=128)),
                ('sei_owner_address', models.CharField(help_text='Current owner address on Sei blockchain', max_length=64)),
                ('name', models.CharField(help_text='NFT name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='NFT description')),
                ('image_url', models.URLField(blank=True, help_text='URL to NFT image')),
                ('external_url', models.URLField(blank=True, help_text='External URL for additional information')),
                ('attributes', models.JSONField(default=dict, help_text='NFT attributes and traits')),
                ('migration_status', models.CharField(choices=[('pending', 'Pending Migration'), ('in_progress', 'Migration In Progress'), ('completed', 'Migration Completed'), ('failed', 'Migration Failed'), ('rolled_back', 'Migration Rolled Back')], db_index=True, default='pending', help_text='Current migration status', max_length=20)),
                ('solana_mint_address', models.CharField(blank=True, db_index=True, help_text='Solana mint address after migration', max_length=44)),
                ('solana_asset_id', models.CharField(blank=True, db_index=True, help_text='Solana compressed NFT asset ID', max_length=64)),
                ('migration_date', models.DateTimeField(blank=True, help_text='Date when migration was completed', null=True)),
                ('sei_data_hash', models.CharField(help_text='Hash of original Sei data for integrity verification', max_length=64)),
                ('validation_errors', models.JSONField(default=list, help_text='List of validation errors encountered')),
                ('migration_job', models.ForeignKey(blank=True, help_text='Associated migration job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sei_nfts', to='blockchain.migrationjob')),
            ],
            options={
                'verbose_name': 'Sei NFT',
                'verbose_name_plural': 'Sei NFTs',
                'db_table': 'blockchain_sei_nft',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the log entry', primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='Log level', max_length=10)),
                ('event_type', models.CharField(choices=[('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_failed', 'Job Failed'), ('job_cancelled', 'Job Cancelled'), ('data_export', 'Data Export'), ('data_mapping', 'Data Mapping'), ('data_validation', 'Data Validation'), ('nft_migration', 'NFT Migration'), ('rollback', 'Rollback'), ('error', 'Error')], db_index=True, help_text='Type of event being logged', max_length=20)),
                ('message', models.TextField(help_text='Log message')),
                ('details', models.JSONField(default=dict, help_text='Additional details and context')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code (if applicable)', max_length=50)),
                ('stack_trace', models.TextField(blank=True, help_text='Stack trace for errors')),
                ('migration_job', models.ForeignKey(help_text='Associated migration job', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='blockchain.migrationjob')),
                ('sei_nft', models.ForeignKey(blank=True, help_text='Associated Sei NFT (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='blockchain.seinft')),
            ],
            options={
                'verbose_name': 'Migration Log',
                'verbose_name_plural': 'Migration Logs',
                'db_table': 'blockchain_migration_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='seinft',
            index=models.Index(fields=['sei_contract_address', 'sei_token_id'], name='blockchain__sei_con_865c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='seinft',
            index=models.Index(fields=['migration_status'], name='blockchain__migrati_32fd73_idx'),
        ),
        migrations.AddIndex(
            model_name='seinft',
            index=models.Index(fields=['solana_mint_address'], name='blockchain__solana__de463f_idx'),
        ),
        migrations.AddIndex(
            model_name='seinft',
            index=models.Index(fields=['migration_job'], name='blockchain__migrati_840bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='seinft',
            index=models.Index(fields=['created_at'], name='blockchain__created_0e11f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seinft',
            unique_together={('sei_contract_address', 'sei_token_id')},
        ),
        migrations.AddIndex(
            model_name='migrationlog',
            index=models.Index(fields=['migration_job', 'created_at'], name='blockchain__migrati_ad005a_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationlog',
            index=models.Index(fields=['sei_nft', 'created_at'], name='blockchain__sei_nft_2efd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationlog',
            index=models.Index(fields=['level'], name='blockchain__level_1c6646_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationlog',
            index=models.Index(fields=['event_type'], name='blockchain__event_t_300288_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationlog',
            index=models.Index(fields=['created_at'], name='blockchain__created_47221e_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['status'], name='blockchain__status_957cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['created_at'], name='blockchain__created_34c2be_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['started_at'], name='blockchain__started_56df28_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['completed_at'], name='blockchain__complet_996baf_idx'),
        ),
    ]
