# Generated by Django 4.2.7 on 2025-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_migrationjob_seinft_migrationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationlog',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code (if applicable)', max_length=50, null=True),
        ),
    ]
