# Generated by Django 4.2.7 on 2025-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_migrationlog_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationlog',
            name='stack_trace',
            field=models.TextField(blank=True, help_text='Stack trace for errors', null=True),
        ),
    ]
