# Generated by Django 4.2.7 on 2025-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_batchmigrationstatus_integrationtestresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seinft',
            name='is_real_onchain',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this NFT was actually minted on-chain (not simulated)'),
        ),
        migrations.AddField(
            model_name='seinft',
            name='solana_metadata_uri',
            field=models.URLField(blank=True, help_text='URI to off-chain metadata stored for Solana NFT'),
        ),
        migrations.AddField(
            model_name='seinft',
            name='solana_transaction_signature',
            field=models.CharField(blank=True, db_index=True, help_text='Solana transaction signature for minting', max_length=88),
        ),
        migrations.AddField(
            model_name='seinft',
            name='solana_tree_address',
            field=models.CharField(blank=True, db_index=True, help_text='Solana Merkle tree address for compressed NFT', max_length=44),
        ),
    ]
